name: Build Spring Boot Application and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: app

    - name: list files
      run: ls

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v1
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: 'us-east-1'
        application_name: 'springboot-actions'
        environment_name: 'Springboot-actions-env'
        version_label: 'helloworld-${{ github.run_number }}'
        deployment_package: 'helloworld-0.0.1-SNAPSHOT.jar'
        #source_bundle: 'app.zip'
